export const CHANGE_SEARCHFIELD = 'CHANGE_SEARCHFIELD';
export const REQUEST_MOVIES_PENDING = 'REQUEST_MOVIES_PENDING';
export const REQUEST_MOVIES_SUCCESS = 'REQUEST_MOVIES_SUCCES';
export const REQUEST_MOVIES_FAILED = 'REQUEST_MOVIES_FAILED'; 